support cleaning files by extensions
spatie/laravel-directory-cleanup pull request #44
Opened 2021-03-05 09:39 UTC by nguyenhiepvan

2021-03-05 10:04 UTC, freekmurze commented
Please make sure that all tests pass.

2021-03-05 16:32 UTC, nguyenhiepvan commented
> Please make sure that all tests pass.

done

2021-03-07 19:18 UTC, freekmurze requested changes
Please add tests that prove that the new functionality is working correctly.

Also add examples of the new functionality to the docs.

2021-03-07 19:18 UTC, freekmurze commented on src/DirectoryCleaner.php
> +                }else{
Avoid using `else`. Maybe you could add a protected function `shouldDelete` and use early returns there.

2021-03-07 19:18 UTC, freekmurze commented on src/DirectoryCleaner.php
> +        if ($extensions && $extensions != "*"){
Please use strict comparisons.

Use an early return if you don't want to do anything on `*`

2021-03-12 22:11 UTC, freekmurze commented
To keep the package as simple as it can be, I've decided not to merge this in.

I don't need the changes myself and I haven't received request for this, from other users.

But your work is not lost: feel free to create a fork and apply your changes there.

Thank you!

2021-03-12 22:11 UTC, closed without merging